-- 1. Drop existing default on id
ALTER TABLE workcenter ALTER COLUMN id DROP DEFAULT;

-- 2. Convert to identity column (recommended)
ALTER TABLE workcenter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;