CREATE TABLE workCenterShift (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workCenterId INT NOT NULL,
    shiftName VARCHAR(50) NOT NULL,
    startTime TIME NOT NULL,
    endTime TIME NOT NULL,
    breakMinutes INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    allowShiftOverlap BOOLEAN NOT NULL DEFAULT FALSE,
    shiftCode VARCHAR(20) NOT NULL,
    plannedCapacityMinutes INT NOT NULL,
    creationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedDate TIMESTAMP,
    deletedDate TIMESTAMP,
    CONSTRAINT fk_workCenterShift_workCenter FOREIGN KEY (workCenterId)
        REFERENCES workcenter(id)
        ON DELETE CASCADE,
    CONSTRAINT uk_wc_shift_name UNIQUE (workCenterId, shiftName),
    CONSTRAINT uk_wc_shift_code UNIQUE (workCenterId, shiftCode),
    CONSTRAINT chk_workCenterShift_breakMinutes_non_negative CHECK (breakMinutes >= 0),
    CONSTRAINT chk_workCenterShift_capacity_non_negative CHECK (plannedCapacityMinutes >= 0)
);

CREATE INDEX idx_wc_shift_work_center ON workCenterShift(workCenterId);
CREATE INDEX idx_wc_shift_active ON workCenterShift(active);

CREATE TABLE workCenterShiftDays (
    shiftId BIGINT NOT NULL,
    dayOfWeek VARCHAR(20) NOT NULL,
    CONSTRAINT fk_workCenterShiftDays_shift FOREIGN KEY (shiftId)
        REFERENCES workCenterShift(id)
        ON DELETE CASCADE,
    CONSTRAINT uk_shift_day UNIQUE (shiftId, dayOfWeek)
);

CREATE INDEX idx_shift_days_shift ON workCenterShiftDays(shiftId);
