CREATE TABLE holidayCalendar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE holidayCalendarWeeklyOffDays (
    holidayCalendarId BIGINT NOT NULL,
    dayOfWeek VARCHAR(20) NOT NULL,
    CONSTRAINT fk_hc_weeklyoff_calendar FOREIGN KEY (holidayCalendarId)
        REFERENCES holidayCalendar(id)
        ON DELETE CASCADE,
    CONSTRAINT uk_hc_weeklyoff UNIQUE (holidayCalendarId, dayOfWeek)
);

CREATE INDEX idx_hc_weeklyoff_calendar ON holidayCalendarWeeklyOffDays(holidayCalendarId);

CREATE TABLE holiday (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holidayCalendarId BIGINT NOT NULL,
    holidayDate DATE NOT NULL,
    name VARCHAR(150) NOT NULL,
    fullDay BOOLEAN NOT NULL DEFAULT TRUE,
    startTime TIME,
    endTime TIME,
    CONSTRAINT fk_holiday_calendar FOREIGN KEY (holidayCalendarId)
        REFERENCES holidayCalendar(id)
        ON DELETE CASCADE,
    CONSTRAINT uk_calendar_date UNIQUE (holidayCalendarId, holidayDate),
    CONSTRAINT chk_holiday_time_window CHECK (
        (fullDay = TRUE AND startTime IS NULL AND endTime IS NULL)
        OR
        (fullDay = FALSE AND startTime IS NOT NULL AND endTime IS NOT NULL AND endTime > startTime)
    )
);

CREATE INDEX idx_holiday_calendar_date ON holiday(holidayCalendarId, holidayDate);

CREATE TABLE calendarOverride (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holidayCalendarId BIGINT NOT NULL,
    overrideDate DATE NOT NULL,
    overrideType VARCHAR(20) NOT NULL,
    reason VARCHAR(300),
    CONSTRAINT fk_calendarOverride_calendar FOREIGN KEY (holidayCalendarId)
        REFERENCES holidayCalendar(id)
        ON DELETE CASCADE,
    CONSTRAINT uk_calendar_override UNIQUE (holidayCalendarId, overrideDate)
);

CREATE INDEX idx_calendar_override_date ON calendarOverride(holidayCalendarId, overrideDate);

ALTER TABLE workCenter
    ADD COLUMN IF NOT EXISTS holidayCalendarId BIGINT;

ALTER TABLE workCenter
    DROP CONSTRAINT IF EXISTS fk_workcenter_holidaycalendar;

ALTER TABLE workCenter
    ADD CONSTRAINT fk_workcenter_holidaycalendar
    FOREIGN KEY (holidayCalendarId)
    REFERENCES holidayCalendar(id)
    ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_workcenter_holidaycalendar ON workCenter(holidayCalendarId);
