ALTER TABLE machinedetails
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS machineStatusHistory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machineId BIGINT NOT NULL,
    oldStatus VARCHAR(30),
    newStatus VARCHAR(30) NOT NULL,
    changedAt TIMESTAMP NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changedBy VARCHAR(100),
    reason VARCHAR(500),
    source VARCHAR(20) NOT NULL,
    CONSTRAINT fk_msh_machine FOREIGN KEY (machineId)
        REFERENCES machineDetails(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_msh_machine_changed_At
    ON machineStatusHistory(machineId, changedAt);

CREATE TABLE IF NOT EXISTS machineEvent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machineId BIGINT NOT NULL,
    eventType VARCHAR(30) NOT NULL,
    startTime TIMESTAMP NOT NULL,
    endTime TIMESTAMP,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(20) NOT NULL,
    CONSTRAINT fk_me_machine FOREIGN KEY (machineId)
        REFERENCES machineDetails(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_me_machine_start_time
    ON machineEvent(machineId, startTime);

CREATE UNIQUE INDEX IF NOT EXISTS uk_me_single_active_per_machine
    ON machineEvent(machineId)
    WHERE endTime IS NULL;

CREATE TABLE IF NOT EXISTS machineProductionLog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    machineId BIGINT NOT NULL,
    productionDate DATE NOT NULL,
    shiftId BIGINT,
    plannedQuantity INT,
    actualQuantity INT,
    rejectedQuantity INT,
    runtimeMinutes INT,
    downtimeMinutes INT,
    CONSTRAINT fk_mpl_machine FOREIGN KEY (machineId)
        REFERENCES machineDetails(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_mpl_planned_non_negative CHECK (plannedQuantity IS NULL OR plannedQuantity >= 0),
    CONSTRAINT chk_mpl_actual_non_negative CHECK (actualQuantity IS NULL OR actualQuantity >= 0),
    CONSTRAINT chk_mpl_rejected_non_negative CHECK (rejectedQuantity IS NULL OR rejectedQuantity >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_mpl_machine_date_shift
    ON machineProductionLog(machineId, productionDate, COALESCE(shiftId, -1));

CREATE INDEX IF NOT EXISTS idx_mpl_machine_date
    ON machineProductionLog(machineId, productionDate);

CREATE TABLE IF NOT EXISTS ScheduleDecisionLog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orderId BIGINT NOT NULL,
    machineId BIGINT NOT NULL,
    scheduledStart TIMESTAMP,
    scheduledEnd TIMESTAMP,
    reason VARCHAR(1000),
    CONSTRAINT fk_sdl_machine FOREIGN KEY (machineId)
        REFERENCES machineDetails(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_sdl_machine_time
    ON ScheduleDecisionLog(machineId, scheduledStart);
