-- ============================================================================
-- V60: Create QC Testing tables (TestTemplate + WorkOrderTestResult)
-- Phase 1.5: QC Testing Feature
-- ============================================================================

-- ─── TestTemplate ───────────────────────────────────────────────────────────
-- Reusable QC test definitions anchored to InventoryItem.
-- When a WorkOrder is created, active templates are copied as frozen snapshots.
CREATE TABLE IF NOT EXISTS testtemplate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    inventoryitemid INTEGER NOT NULL,

    testname VARCHAR(150) NOT NULL,
    inspectiontype VARCHAR(30) NOT NULL,
    samplesize INTEGER,
    ismandatory BOOLEAN NOT NULL DEFAULT TRUE,
    sequence INTEGER,
    acceptancecriteria VARCHAR(500),
    unitofmeasure VARCHAR(20),
    minvalue NUMERIC(15,5),
    maxvalue NUMERIC(15,5),

    active BOOLEAN NOT NULL DEFAULT TRUE,

    creationdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateddate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleteddate TIMESTAMP,

    CONSTRAINT fk_tt_inventory_item
        FOREIGN KEY (inventoryitemid)
        REFERENCES inventoryitem(inventoryitemid)
);

CREATE INDEX IF NOT EXISTS idx_tt_item
    ON testtemplate(inventoryitemid);

-- ─── WorkOrderTestResult ────────────────────────────────────────────────────
-- Frozen snapshot of TestTemplate for a specific Work Order.
-- Operators fill in actual test results here.
CREATE TABLE IF NOT EXISTS workordertestresult (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    workorderid BIGINT NOT NULL,
    testtemplateid BIGINT,

    -- Snapshot from template (frozen at WO creation)
    testname VARCHAR(150),
    inspectiontype VARCHAR(30),
    samplesize INTEGER,
    ismandatory BOOLEAN,
    sequence INTEGER,
    acceptancecriteria VARCHAR(500),
    unitofmeasure VARCHAR(20),
    minvalue NUMERIC(15,5),
    maxvalue NUMERIC(15,5),

    -- Actual results (filled by operator)
    resultvalue NUMERIC(15,5),
    testedquantity INTEGER,
    passedquantity INTEGER,
    failedquantity INTEGER,
    result VARCHAR(20) DEFAULT 'PENDING',
    testedby VARCHAR(100),
    testdate TIMESTAMP,
    remarks VARCHAR(500),

    creationdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateddate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_wotr_work_order
        FOREIGN KEY (workorderid)
        REFERENCES workorder(id),

    CONSTRAINT fk_wotr_test_template
        FOREIGN KEY (testtemplateid)
        REFERENCES testtemplate(id)
);

CREATE INDEX IF NOT EXISTS idx_wotr_wo
    ON workordertestresult(workorderid);

CREATE INDEX IF NOT EXISTS idx_wotr_template
    ON workordertestresult(testtemplateid);
